---
- name: Run nginx-prometheus-exporter
  community.docker.docker_container:
    name: nginx_exporter
    image: nginx/nginx-prometheus-exporter:latest
    state: started
    restart_policy: always
    command: ["-nginx.scrape-uri", "http://127.0.0.1:{{ frontend_http_port }}/stub_status"]
    network_mode: host
