env: "staging"
frontend_domain: "{{ staging_domain }}"
mongo_uri: "mongodb+srv://RMIT_Store:123RMIT@rmitstore.uvixzgs.mongodb.net/rmit_ecommerce?retryWrites=true&w=majority&appName=RMITStore"
api_origin: "http://127.0.0.1:3000"
compose_file: "{{ playbook_dir }}/../compose/staging/docker-compose.yml"