---
- name: Ensure monitoring dir
  file:
    path: /opt/monitoring
    state: directory
    mode: '0755'

- name: Put compose.yml
  copy:
    src: "{{ playbook_dir }}/../compose/monitoring/docker-compose.yml"
    dest: /opt/monitoring/docker-compose.yml
    mode: '0644'

- name: Render prometheus.yml
  template:
    src: "{{ playbook_dir }}/../compose/monitoring/prometheus.yml.j2"
    dest: /opt/monitoring/prometheus.yml
    mode: '0644'

- name: Put alertmanager.yml
  copy:
    src: "{{ playbook_dir }}/../compose/monitoring/alertmanager.yml"
    dest: /opt/monitoring/alertmanager.yml
    mode: '0644'

- name: Grafana provisioning
  synchronize:
    src: "{{ playbook_dir }}/../compose/monitoring/grafana/"
    dest: /opt/monitoring/grafana/
    recursive: yes

- name: Bring up monitoring
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    state: present
    pull: always
