route:
  receiver: 'team-email'
receivers:
  - name: 'team-email'
    email_configs:
      - to: "you@example.com"
        from: "alert@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "smtp_user"
        auth_password: "smtp_pass"
